name: RDF Pipeline

on:
  push:
    branches: ["*"]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Generate RDF cube
        run: python main.py
      - uses: actions/upload-artifact@v4
        with:
          name: pipeline-outputs
          path: |
            outputs/
            inputs/

  upload:
    needs: generate
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'PROD' || github.ref_name == 'develop' && 'INT' || 'TEST' }}
    env:
      UPLOAD_METHOD: "PUT"
      UPLOAD_PATH: "outputs"
      ENDPOINT_GRAPH: "https://linked.opendata.swiss/graph/sfoe/energyproduction"
      ENDPOINT_USER: ${{ secrets.ENDPOINT_USER }}
      ENDPOINT_PASSWORD: ${{ secrets.ENDPOINT_PASSWORD }}
      ENDPOINT_URL: ${{ secrets.ENDPOINT_URL }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: pipeline-outputs
      - name: Upload to LINDAS
        run: bash upload.sh
